name: culvert_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - celery
  - redis-py
  - requests
  - geopandas
  - pandas
  - numpy
  - scikit-learn
  - folium
  - python-multipart
  - shapely
  - fiona
  - pyproj
  - gdal
